# Use an official OpenJDK runtime as a parent image
FROM openjdk:21-jdk-slim

# Set the working directory inside the container
WORKDIR /app

# Copy the application's JAR file into the container
COPY target/medilabo*.jar app.jar

# Expose the port the app runs on
EXPOSE 8083

# Run the JAR file
# ENTRYPOINT ["java","-Dspring.profiles.active=docker","-jar", "/app/app.jar"]
ENTRYPOINT ["java","-Dspring.config.location=classpath:/application-docker.properties","-jar","/app/app.jar"]
